apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"load"},"name":"load","namespace":"default"}}
  creationTimestamp: "2024-06-03T17:24:13Z"
  labels:
    app: load
  name: load
  namespace: default
  resourceVersion: "902501"
  uid: 3dcb4fe2-fc99-4b9d-93b4-2b75e37971d1
